"""Initial schema

Revision ID: 3f3b9f2ab218
Revises:
Create Date: 2026-08-24 08:37:41.473789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3b9f2ab218'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_code'), 'exchanges', ['code'], unique=True)
    op.create_index(op.f('ix_exchanges_is_active'), 'exchanges', ['is_active'], unique=False)
    op.create_table('market_data_providers',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.Enum('REST_API', 'WEBSOCKET', 'FILE', 'MANUAL', name='providertype'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_providers_code'), 'market_data_providers', ['code'], unique=True)
    op.create_table('news_articles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_published', 'news_articles', ['published_at'], unique=False, postgresql_ops={'published_at': 'DESC'})
    op.create_index('ix_news_source', 'news_articles', ['source'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_table('instruments',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('instrument_type', sa.Enum('EQUITY', 'ETF', 'INDEX', 'BOND', 'DERIVATIVE', 'CURRENCY', name='instrumenttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'symbol', name='uq_exchange_symbol')
    )
    op.create_index('ix_instrument_active', 'instruments', ['is_active'], unique=False)
    op.create_index('ix_instrument_isin', 'instruments', ['isin'], unique=False)
    op.create_index('ix_instrument_symbol', 'instruments', ['symbol'], unique=False)
    op.create_index('ix_instrument_type', 'instruments', ['instrument_type'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_user', 'portfolios', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_user', 'watchlists', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_user', 'workspaces', ['user_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'fiscal_year', 'fiscal_quarter', name='uq_fundamental_period')
    )
    op.create_index('ix_fundamental_instrument', 'fundamentals', ['instrument_id'], unique=False)
    op.create_index('ix_fundamental_period', 'fundamentals', ['period_end_date'], unique=False)
    op.create_table('news_article_instruments',
    sa.Column('news_article_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_article_id', 'instrument_id')
    )
    op.create_index('ix_news_inst_article', 'news_article_instruments', ['news_article_id'], unique=False)
    op.create_index('ix_news_inst_instrument', 'news_article_instruments', ['instrument_id'], unique=False)
    op.create_table('ohlcv',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'instrument_id', 'interval')
    )
    op.create_index('ix_ohlcv_instrument_interval_time', 'ohlcv', ['instrument_id', 'interval', 'time'], unique=False, postgresql_ops={'time': 'DESC'})
    op.create_index('ix_ohlcv_source', 'ohlcv', ['source'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('average_cost', sa.Numeric(), nullable=False),
    sa.Column('current_price', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name='uq_portfolio_instrument')
    )
    op.create_index('ix_position_instrument', 'portfolio_positions', ['instrument_id'], unique=False)
    op.create_index('ix_position_portfolio', 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'SPLIT', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_date', 'portfolio_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_transaction_instrument', 'portfolio_transactions', ['instrument_id'], unique=False)
    op.create_index('ix_transaction_portfolio', 'portfolio_transactions', ['portfolio_id'], unique=False)
    op.create_table('provider_symbols',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('provider_symbol', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['market_data_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'instrument_id', name='uq_provider_instrument'),
    sa.UniqueConstraint('provider_id', 'provider_symbol', name='uq_provider_symbol_code')
    )
    op.create_index('ix_provider_symbol_instrument', 'provider_symbols', ['instrument_id'], unique=False)
    op.create_index('ix_provider_symbol_provider', 'provider_symbols', ['provider_id'], unique=False)
    op.create_table('quotes',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('bid_price', sa.Numeric(), nullable=True),
    sa.Column('ask_price', sa.Numeric(), nullable=True),
    sa.Column('last_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('bid_size', sa.BigInteger(), nullable=True),
    sa.Column('ask_size', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'instrument_id')
    )
    op.create_index('ix_quotes_instrument_time', 'quotes', ['instrument_id', 'time'], unique=False, postgresql_ops={'time': 'DESC'})
    op.create_index('ix_quotes_source', 'quotes', ['source'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_instrument')
    )
    op.create_index('ix_watchlist_item_instrument', 'watchlist_items', ['instrument_id'], unique=False)
    op.create_index('ix_watchlist_item_watchlist', 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('workspace_panels',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('panel_type', sa.String(), nullable=False),
    sa.Column('panel_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_panel_workspace', 'workspace_panels', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


    # Add TimescaleDB hypertables
    op.execute("SELECT create_hypertable('quotes', 'time', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('ohlcv', 'time', if_not_exists => TRUE);")


def downgrade() -> None:
    # Drop TimescaleDB hypertables
    # Note: dropping the table automatically drops the hypertable in TimescaleDB
    pass
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_panel_workspace', table_name='workspace_panels')
    op.drop_table('workspace_panels')
    op.drop_index('ix_watchlist_item_watchlist', table_name='watchlist_items')
    op.drop_index('ix_watchlist_item_instrument', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('ix_quotes_source', table_name='quotes')
    op.drop_index('ix_quotes_instrument_time', table_name='quotes', postgresql_ops={'time': 'DESC'})
    op.drop_table('quotes')
    op.drop_index('ix_provider_symbol_provider', table_name='provider_symbols')
    op.drop_index('ix_provider_symbol_instrument', table_name='provider_symbols')
    op.drop_table('provider_symbols')
    op.drop_index('ix_transaction_portfolio', table_name='portfolio_transactions')
    op.drop_index('ix_transaction_instrument', table_name='portfolio_transactions')
    op.drop_index('ix_transaction_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index('ix_position_portfolio', table_name='portfolio_positions')
    op.drop_index('ix_position_instrument', table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_ohlcv_source', table_name='ohlcv')
    op.drop_index('ix_ohlcv_instrument_interval_time', table_name='ohlcv', postgresql_ops={'time': 'DESC'})
    op.drop_table('ohlcv')
    op.drop_index('ix_news_inst_instrument', table_name='news_article_instruments')
    op.drop_index('ix_news_inst_article', table_name='news_article_instruments')
    op.drop_table('news_article_instruments')
    op.drop_index('ix_fundamental_period', table_name='fundamentals')
    op.drop_index('ix_fundamental_instrument', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_workspace_user', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_watchlist_user', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_portfolio_user', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_instrument_type', table_name='instruments')
    op.drop_index('ix_instrument_symbol', table_name='instruments')
    op.drop_index('ix_instrument_isin', table_name='instruments')
    op.drop_index('ix_instrument_active', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_news_source', table_name='news_articles')
    op.drop_index('ix_news_published', table_name='news_articles', postgresql_ops={'published_at': 'DESC'})
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_data_providers_code'), table_name='market_data_providers')
    op.drop_table('market_data_providers')
    op.drop_index(op.f('ix_exchanges_is_active'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_code'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
